import React from 'react'

const Privacy = () => {
  return (
    <div className="min-h-screen py-10 md:py-10 px-6 sm:px-10">
      {/* Max-width 3xl is the "Gold Standard" for reading long text */}
      <article className="max-w-3xl mx-auto">

        <h1 className="font-heading text-4xl md:text-5xl font-extrabold text-black mb-8 tracking-tighter">
          Privacy Policy
        </h1>
        {/* <p className="text-gray-500 font-body mb-12 text-sm">Last Updated: March 01, 2026</p> */}

        {/* Content Section - Using specific styling for legal text */}
        <div className="font-body text-gray-700 leading-relaxed space-y-12">
          
          <section>
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, 
              use, and disclosure of Your information when You use the Disciplinex
              application and informs You about Your privacy rights and how the law protects You.
            </p>
            <p className="mt-4">
              By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>

          <section className="bg-gray-50 p-6 rounded-2xl border border-gray-100">
            <h2 className="text-xl font-bold text-black mb-4">Quick Summary</h2>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>We collect basic data like Name and Email.</li>
              <li>We <strong>never</strong> sell your data to third parties.</li>
              <li>Data is used solely to improve your DisciplineX experience.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black mb-5">1. Interpretation and Definitions</h2>
            <h3 className="text-lg font-semibold text-black mb-2">Interpretation</h3>
            <p className="mb-4">
              Words with capitalized initial letters have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
            </p>
            
            <h3 className="text-lg font-semibold text-black mb-2">Definitions</h3>
            <p className="mb-3">For the purposes of this Privacy Policy:</p>
            <ul className="list-none pl-0 space-y-3 text-gray-700">
              <li><strong>Application</strong> refers to the software program named "DisciplineX" provided by the Developer.</li>
              <li><strong>Developer</strong> ("We", "Us", or "Our") refers to Ashutosh Kumar.</li>
              <li><strong>Country</strong> refers to India.</li>
              <li><strong>Device</strong> means any device that can access the Application, such as a smartphone, tablet, or computer.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Application.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service.</li>
              <li><strong>You</strong> refers to the individual using the Service or the company or legal entity on behalf of which such individual is using the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black mb-5">2. Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-lg font-semibold text-black mb-2">Types of Data Collected</h3>
            <p className="font-semibold text-black mt-4">Personal Data</p>
            <p className="mb-2">While using Our Service, We may ask You to provide certain personally identifiable information, including but not limited to:</p>
            <ul className="list-disc pl-5 mb-4">
              <li>Name</li>
              <li>Email address</li>
              <li>Contact information</li>
            </ul>

            <p className="font-semibold text-black mt-4">Usage Data</p>
            <p className="mb-2">Usage Data is collected automatically when using the Service. This may include:</p>
            <ul className="list-disc pl-5 mb-4">
              <li>Device Internet Protocol (IP) address</li>
              <li>Browser type and version</li>
              <li>Pages of our Service You visit</li>
              <li>Time and date of Your visit</li>
              <li>Unique device identifiers</li>
            </ul>

            <h3 className="text-lg font-semibold text-black mt-6 mb-2">How We Use Your Data</h3>
            <p className="mb-3">We may use Your information for the following purposes:</p>
            <ol className="list-decimal pl-5 space-y-2">
              <li>To provide and maintain our Service</li>
              <li>To manage Your account</li>
              <li>To improve the user experience</li>
              <li>To communicate with You</li>
              <li>To comply with legal obligations</li>
            </ol>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black mb-5">3. Sharing and Security</h2>
            
            <h3 className="text-lg font-semibold text-black mb-2">Sharing Your Data</h3>
            <p className="mb-3">We do not sell, trade, or rent Your Personal Data. However, We may share Your information:</p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li><strong>With Service Providers:</strong> To facilitate our Service.</li>
              <li><strong>For Legal Reasons:</strong> If required by law or valid legal requests.</li>
            </ul>

            <h3 className="text-lg font-semibold text-black mt-6 mb-2">Data Retention</h3>
            <p className="mb-4">We retain Your Personal Data only as long as necessary for the purposes outlined in this Privacy Policy.</p>

            <h3 className="text-lg font-semibold text-black mt-6 mb-2">Security of Your Data</h3>
            <p>We take reasonable precautions to protect Your Personal Data. However, no method of transmission over the Internet is 100% secure.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black mb-5">4. Your Privacy Rights</h2>
            <p className="mb-3">Depending on Your location, You may have rights regarding Your Personal Data:</p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li>The right to access, update, or delete Your Personal Data.</li>
              <li>The right to withdraw consent.</li>
              <li>The right to object to data processing.</li>
              <li>The right to data portability.</li>
            </ul>
            <p>To exercise Your rights, please contact Us at <strong><a href="mailto:aasshhuutosh1@gmail.com" className="text-black hover:underline">aasshhuutosh1@gmail.com</a></strong>.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black mb-5">5. Children's Privacy</h2>
            <p>Our Service is not intended for children under 18, and We do not knowingly collect Personal Data from children.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black mb-5">6. Changes to This Privacy Policy</h2>
            <p>We may update this Privacy Policy from time to time. Any changes will be posted on this page.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black mb-5">7. Contact Us</h2>
            <p>If You have any questions about this Privacy Policy, You can contact Us at:</p>
            <p className="mt-2 font-semibold">Email: <a href="mailto:aasshhuutosh1@gmail.com" className="text-black hover:underline">aasshhuutosh1@gmail.com</a></p>
          </section>
          
        </div>
      </article>
    </div>
  )
}

export default Privacy